In [1]:
!python -V

Python 3.12.1


In [2]:
import numpy as mp

In [3]:
u = mp.array([2,7,5,6])

In [4]:
v = mp.array([4,6,3,9])

In [5]:
# Addition
u + v

array([ 6, 13,  8, 15])

In [6]:
# Substraction
u - v

array([-2,  1,  2, -3])

In [7]:
# Scalar Multiplication
4 * u

array([ 8, 28, 20, 24])

In [8]:
# Vector Multiplication
u * v

array([ 8, 42, 15, 54])